language: csharp
mono: none
dotnet: 3.1
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_script:
  - psql -c 'create database nsi_pricing;' -U postgres
  - psql -c "create role nsi_user login password 'nsi_pass';" -U postgres
  - psql -c "grant all privileges on database nsi_pricing to nsi_user;"  -U postgres
script:
  - dotnet restore
  - dotnet build